version: '3.9'

services:
  app:
    user: '1000'
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:8081:8081
    environment:
      NODE_ARGS: --inspect=0.0.0.0:9229
    command: ['yarn', '_dev']
