version: '3.9'
services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ws_url: $WS_URL
    volumes:
      - logs:/app/logs
    env_file: .env

volumes:
  logs: {}
